<?php

/**
 * @file
 * A module that allows you to add recipes in a form
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function rasrobin_recipes_help($path, $arg) {
  switch ($path) {
  case "admin/help#rasrobin_recipes":
    return t("Show a form to add recipes"); 
    break; 
  }
}

function rasrobin_recipes_menu() {
  $items = [];

  $items['recipe/add'] = [ //this creates a URL that will call this form at "recipes/add-recipe"
    'title' => 'Submit a recipe', //page title
    'description' => 'Here you can add a recipe',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => ['rasrobin_recipes_form_add'], //put the name of the form here
    'access callback' => TRUE
  ];

  return $items;
}

/**
 * The form - add recipe form
 */
function rasrobin_recipes_form_add($form, &$form_state) {
  $form['title'] = [
    '#type' => 'textfield',
    '#title' => 'recipe title',
    '#size' => 20,
    '#maxlength' => 255,
    '#required' => TRUE, 
  ];

  $form['author_name'] = [
    '#type' => 'textfield',
    '#title' => 'Author name',
    '#size' => 20,
    '#maxlength' => 255,
    '#required' => FALSE,
  ];

  $form['author_email'] = [
    '#type' => 'textfield',
    '#title' => 'Author e-mail',
    '#size' => 20,
    '#maxlength' => 255,
    '#required' => TRUE,
  ];

  $form['description'] = [
    '#type' => 'textarea',
    '#title' => 'Recipe description',
    '#maxlength' => 500,
    '#required' => FALSE,
  ];

  $form['instructions'] = [
    '#type' => 'textarea',
    '#title' => 'Recipe instructions',
    '#required' => FALSE,
  ];

  $form['ingredients'] = [
    '#type' => 'textarea',
    '#title' => 'Recipe ingredients',
    '#required' => TRUE,
  ];

  $form['submit_button'] = [
    '#type' => 'submit',
    '#value' => t('Submit recipe'),
  ];
  
  return $form;
}

/**
 * Validate - add recipe form
 */
function rasrobin_recipes_form_add_validate($form, &$form_state) {
	//
}

/**
 * Submit - add recipe form
 */
function rasrobin_recipes_form_add_submit($form, &$form_state) {
	//
}
