<?php

/**
 * @file
 * A module that allows you to add recipes in a form
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function rasrobin_recipes_help($path, $arg) {
  switch ($path) {
  case "admin/help#rasrobin_recipes":
    return t("Show a form to add recipes"); 
    break; 
  }
}

/**
 * The form - add recipe form
 */
function form_add_recipe($form, &$form_state) {
  
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Add!'),
  ];
  
  return $form;
}

/**
 * Validate - add recipe form
 */
function form_add_recipe_validate($form, &$form_state) {
	//
}

/**
 * Submit - add recipe form
 */
function form_add_recipe_submit($form, &$form_state) {
	//
}
