<?php

/**
 * @file
 * Creating the database structure for the module
 */

/**
 * Implements hook_schema().
 */
function rasrobin_recipes_schema() {
  $schema['_rasrobin_recipes'] = [
		'description' => 'A table for recipes',
	    'fields' => [
	      'id' => [
	        'description' => 'The primary identifier for a recipe',
	        'type' => 'int',
	        'unsigned' => TRUE,
	        'not null' => TRUE
	      ],
	    ],
	  'primary_key' => array('id'),
  ];

  return $schema;
}