<?php

/**
 * @file
 * A module that allows you to add recipes in a form
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function rasrobin_recipes_help($path, $arg) {
  switch ($path) {
  case "admin/help#rasrobin_recipes":
    return t("Show a form to add recipes"); 
    break; 
  }
}

function rasrobin_recipes_menu() {
  $items = [];

  $items['recipes/add-recipe'] = [ //this creates a URL that will call this form at "recipes/add-recipe"
    'title' => 'Add a recipe', //page title
    'description' => 'Here you can add a recipe',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => ['rasrobin_recipes_form_add'], //put the name of the form here
    'access callback' => TRUE
  ];

  return $items;
}

/**
 * The form - add recipe form
 */
function rasrobin_recipes_form_add($form, &$form_state) {
  
  $form['submit_button'] = [
    '#type' => 'submit',
    '#value' => t('Add!'),
  ];
  
  return $form;
}

/**
 * Validate - add recipe form
 */
function rasrobin_recipes_form_add_validate($form, &$form_state) {
	//
}

/**
 * Submit - add recipe form
 */
function rasrobin_recipes_form_add_submit($form, &$form_state) {
	//
}
